services: 
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: $MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_DOCKER_PORT
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", $DB_HOST]
      timeout: 10s
      retries: 5
  back:
    build:
      context: ./packages/back
    ports:
      - $API_PORT:$API_PORT
      - $WS_PORT:$WS_PORT
    expose:
      - $API_PORT
      - $WS_PORT
    depends_on:
      mysqldb:
        condition: service_healthy
    stdin_open: true
    tty: true
  front:
    build:
      context: ./packages/front
    ports:
      - $WEB_PORT:$WEB_PORT
    expose:
      - $WEB_PORT
    depends_on:
      - back
    stdin_open: true
    tty: true
volumes: 
  db-config:
  db-data: