services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  back:
    build:
      context: ./packages/back
    ports:
      - 3001:3001
      - 8000:8000
    expose:
      - '3001'
      - '8000'
    depends_on:
      mysqldb:
        condition: service_healthy
    stdin_open: true
    tty: true
  front:
    build:
      context: ./packages/front
    ports:
      - 3000:3000
    expose:
      - '3000'
    depends_on:
      - back
    stdin_open: true
    tty: true
volumes: 
  db-config:
  db-data: